# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageCollector' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :osx, '10.10'

  # Pods for ImageCollector
  pod 'SDWebImage', '~> 4.0'

end
